version: '3'
name: learning_cards

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - learning_cards_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 100
      start_period: 10s

  spring-java-backend:
    container_name: spring-java-backend
    build:
      context: ./backend
    networks:
      - learning_cards_network
    depends_on:
      mysql-db:
        condition: service_healthy

  vue-nginx-frontend:
    container_name: vue-nginx-frontend 
    build:
      context: ./frontend
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - learning_cards_network
    depends_on:
      - spring-java-backend

  minio-data:
    image: minio/minio
    ports:
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: myminiouser
      MINIO_ROOT_PASSWORD: mysecurepassword
  
    command: server --address ":9000" --console-address ":9001" /data
    networks:
      - learning_cards_network

networks:
  learning_cards_network:
    driver: bridge
