version: '3'

services:
  mysql-db:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - learning_cards_network

  spring-java-backend:
    build:
      context: ./backend
    networks:
      - learning_cards_network
    depends_on:
      - mysql-db

  vue-nginx-frontend:
    build:
      context: ./frontend
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - learning_cards_network
    depends_on:
      - spring-java-backend
  

networks:
  learning_cards_network:
    driver: bridge
