name: Node.js Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: ls frontend
      working-directory: ${{ github.workspace }}/frontend
    - run: npm install  
      working-directory: ${{ github.workspace }}/frontend
    - run: npm run build --if-present
      working-directory: ${{ github.workspace }}/frontend
    - run: npm test
      working-directory: ${{ github.workspace }}/frontend


